  version: '3'
    
  services:
    db:
      image: mysql
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - '3307:3306'
      environment:
        - MYSQL_DATABASE=django
        - MYSQL_USER=django
        - MYSQL_PASSWORD=django
        - MYSQL_ROOT_PASSWORD=root
    web:
      build: .
      container_name: django_project
      command: bash -c "./wait-for-it.sh db:3306 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db

